### ISSUE TITLE
Makefile:35: recipe for target 'build' failed

### ISSUE THREAD

**Issue by kevkha** [briandowns/raceway#13]
I'm on SLE12 running go1.6 and `make build` fails. Not sure it's a race bug yet and wanted to post it here in case someone has run into and hopefully have a solution.

``` bash
# go version
go version go1.6 linux/amd64
```

``` bash
runtime.raceinit: __tsan_init: not defined
runtime.raceinit: __tsan_map_shadow: not defined
runtime.racefini: __tsan_fini: not defined
runtime.racemapshadow: __tsan_map_shadow: not defined
runtime.racemalloc: __tsan_malloc: not defined
runtime.racegostart: __tsan_go_start: not defined
runtime.racegoend: __tsan_go_end: not defined
runtime.raceacquireg: __tsan_acquire: not defined
runtime.racereleaseg: __tsan_release: not defined
runtime.racereleasemergeg: __tsan_release_merge: not defined
runtime.racefingo: __tsan_finalizer_goroutine: not defined
runtime.RaceDisable: __tsan_go_ignore_sync_begin: not defined
runtime.RaceEnable: __tsan_go_ignore_sync_end: not defined
runtime.raceread: __tsan_read: not defined
runtime.racereadpc: __tsan_read_pc: not defined
runtime.racewrite: __tsan_write: not defined
runtime.racewritepc: __tsan_write_pc: not defined
runtime.racereadrange: __tsan_read_range: not defined
runtime.racereadrangepc1: __tsan_read_range: not defined
runtime.racewriterange: __tsan_write_range: not defined
runtime.racewriterangepc1: __tsan_write_range: not defined
/usr/lib64/go/pkg/tool/linux_amd64/link: too many errors
Makefile:35: recipe for target 'build' failed
make: *** [build] Error 2
```

This test obviously also fails

``` bash
# go test -race
# _/root/gocode/raceway
runtime.raceinit: __tsan_init: not defined
runtime.raceinit: __tsan_map_shadow: not defined
runtime.racefini: __tsan_fini: not defined
runtime.racemapshadow: __tsan_map_shadow: not defined
runtime.racemalloc: __tsan_malloc: not defined
runtime.racegostart: __tsan_go_start: not defined
runtime.racegoend: __tsan_go_end: not defined
runtime.raceacquireg: __tsan_acquire: not defined
runtime.racereleaseg: __tsan_release: not defined
runtime.racereleasemergeg: __tsan_release_merge: not defined
runtime.racefingo: __tsan_finalizer_goroutine: not defined
runtime.RaceDisable: __tsan_go_ignore_sync_begin: not defined
runtime.RaceEnable: __tsan_go_ignore_sync_end: not defined
runtime.raceread: __tsan_read: not defined
runtime.racereadpc: __tsan_read_pc: not defined
runtime.racewrite: __tsan_write: not defined
runtime.racewritepc: __tsan_write_pc: not defined
runtime.racereadrange: __tsan_read_range: not defined
runtime.racereadrangepc1: __tsan_read_range: not defined
runtime.racewriterange: __tsan_write_range: not defined
runtime.racewriterangepc1: __tsan_write_range: not defined
/usr/lib64/go/pkg/tool/linux_amd64/link: too many errors
```

**Comment by briandowns** [comment]
Odd. I'm using 1.6 too. I can look next week unless you can debug and research.

**Comment by briandowns** [comment]
What compiler are you using?

**Comment by kevkha** [comment]
I found these

``` bash
================================================================================= Matched: compiler ==================================================================================
gcc.x86_64 : The system GNU C Compiler
gcc-c++.x86_64 : The system GNU C++ Compiler
gcc48.x86_64 : The GNU C Compiler and Support Files
gcc48-c++.x86_64 : The GNU C++ Compiler
libasan0.x86_64 : The GNU Compiler Address Sanitizer Runtime Library
libatomic1.x86_64 : The GNU Compiler Atomic Operations Runtime Library
libgomp1.x86_64 : The GNU compiler collection OpenMP runtime library
libitm1.x86_64 : The GNU Compiler Transactional Memory Runtime Library
libtsan0.x86_64 : The GNU Compiler Thread Sanitizer Runtime Library
binutils.x86_64 : GNU Binutils
gettext-runtime.x86_64 : Tools for Native Language Support (NLS)
gettext-tools.x86_64 : Tools for Native Language Support (NLS)
libgcc_s1.x86_64 : C compiler runtime library
libsemanage1.x86_64 : SELinux binary policy manipulation library
libsepol1.x86_64 : SELinux binary policy manipulation library
perl-JSON-XS.x86_64 : JSON serialising/deserialising, done correctly and fast
```

`# gcc -v`

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/4.8/lto-wrapper
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,java,ada --enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.8 --enable-ssp --disable-libssp --disable-plugin --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --disable-libgcj --disable-libmudflap --with-slibdir=/lib64 --with-system-zlib --enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --enable-linker-build-id --enable-linux-futex --program-suffix=-4.8 --without-system-libunwind --with-arch-32=i586 --with-tune=generic --build=x86_64-suse-linux --host=x86_64-suse-linux
Thread model: posix
gcc version 4.8.3 20140627 [gcc-4_8-branch revision 212064] (SUSE Linux)
```

**Comment by briandowns** [comment]
Make sure the native compiler is used. No cgo issued or necessary.

**Comment by kevkha** [comment]
To workaround this I remove `-race` on line 35 in `Makefile`. Will dig more on `tsan` library later.

**Comment by briandowns** [comment]
Ok. That'll need to go back in at some point since not checking for race conditions is super bad.

**Comment by briandowns** [comment]
Makefile adjusted in #15

**Comment by niranjanreddy891** [comment]
@kevkha, @briandowns, I am facing this issue when running `make` file 
```
niranjan@niranjan:/media/niranjan/dacbdfb3-1124-4d40-94e1-8d36493eaabf/exp-projects/content$ sudo make
./init.sh
experiment publisher already already present
Username for 'https://gitlab.com': niranjanreddy891
Password for 'https://niranjanreddy891@gitlab.com': 
Already up-to-date.
symlinked makefile already present
make -f pub-make -k build
make[1]: Entering directory '/media/niranjan/dacbdfb3-1124-4d40-94e1-8d36493eaabf/exp-projects/content'
rm -rf build
(export PYTHONPATH=`pwd`; python exp-publisher/targets.py target=build)
module make_config not found
module make_config not found
module make_config not found
command: rsync -a /home/niranjan/tmp/experiments/infra/org-exporter-9/elisp ./
rsync: change_dir "/home/niranjan/tmp/experiments/infra/org-exporter-9" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
Called Process Error Message: 
Traceback (most recent call last):
  File "exp-publisher/targets.py", line 73, in <module>
    build()
  File "exp-publisher/targets.py", line 50, in build
    copy_exporter(exporter)
  File "/media/niranjan/dacbdfb3-1124-4d40-94e1-8d36493eaabf/exp-projects/content/exp-publisher/utils.py", line 141, in copy_exporter
    execute_command(cmd)
  File "/media/niranjan/dacbdfb3-1124-4d40-94e1-8d36493eaabf/exp-projects/content/exp-publisher/utils.py", line 213, in execute_command
    raise cpe
subprocess.CalledProcessError: Command 'rsync -a /home/niranjan/tmp/experiments/infra/org-exporter-9/elisp ./' returned non-zero exit status 23
pub-make:23: recipe for target 'build' failed
make[1]: *** [build] Error 1
make[1]: Leaving directory '/media/niranjan/dacbdfb3-1124-4d40-94e1-8d36493eaabf/exp-projects/content'
makefile:12: recipe for target 'build' failed
make: *** [build] Error 2
```
I am running on Ubuntu-16.04.
